### ISSUE TITLE
각각의 집회or모임 구분용 데이터 필요함

### ISSUE THREAD

**Issue by kimhanui** [jkey20/Interface_Android#2]
모임에 출석한 회원을 `날짜`별로 구분한다면  
-> 하루에 두 개 이상의 집회나 모임에서 출첵을 하는 일이 생길시 `각 모임의 명단 분리 불가능`

클라이언트에서 모임별로 구분할만한 데이터를 따로 전송해주나요?
또는 출석key만으로도 구분이 되나요??

@jkey20

**Comment by dev210202** [comment]
출석체크시 암호를 받기때문에 각 집회 or 모임시 암호가 다 다르므로 암호로 구별하면 됩니당
@kimhanui

**Comment by kimhanui** [comment]
모든 집회, 모임에서 출석암호가 달라지나요 ?  
관리자가 수동으로 설정한다면 출석암호가 과거의 모임과 중복될 가능성도 있을 것 같은데, 출석암호 생성 방법을 따로 생각해놓으신건가요 ??
@jkey20

**Comment by dev210202** [comment]
관리자가 암호를 설정할때 기존에 서버에 저장되어있는 암호라면 다시 설정하게 해주게 하면 출석암호를 계속 다르게 할 수 있습니당
@kimhanui
