### ISSUE TITLE
공지사항 데이터 형식 수정요청

### ISSUE THREAD

**Issue by dev210202** [jkey20/Interface_Android#3]
save에서 author는 삭제해도 될것같습니다
@kimhanui

**Comment by dev210202** [comment]
findAll에서 
```java
[{"id":1,"title":"집회","author":"서기","modifiedDate":"2020-08-13 03:17"}]
```
 이 형식으로 결과값을 주는데 content가 빠져있습니다
@kimhanui

**Comment by kimhanui** [comment]
> save에서 author는 삭제해도 될것같습니다
> @kimhanui

**확인**




> findAll에서
> 
> ```java
> [{"id":1,"title":"집회","author":"서기","modifiedDate":"2020-08-13 03:17"}]
> ```
> 
> 이 형식으로 결과값을 주는데 content가 빠져있습니다
> @kimhanui

이 부분은 공지사항을 리스트로 뿌렸을 때   
아래처럼 보일 것 같아서 그렇슴다(실제 웹으로 접속했을 때 모습)
![image](https://user-images.githubusercontent.com/30483337/92347145-fe335c80-f109-11ea-8e9c-d808a38b645a.png)
이런 디자인이면 `content`는 게시글 하나만 찾는 url에서만 쓰이도록 해도 충분하기 때문이에요

이런 디자인이 아니라면 바꿀게요 reply주세욤
@jkey20

**Comment by dev210202** [comment]
아직 디자인을 제대로 받지못해서 디자인이 나오면 알려드리겠습니다 일단은 지금 방식대로 할게요
@kimhanui
