### ISSUE TITLE
db 용량관련

### ISSUE THREAD

**Issue by kimhanui** [jkey20/Interface_Android#4]
동아리 전체 회원을 db에 담으려면 용량이 꽤 될 것 같은데..    
엑셀로는 용량이 어느 정도 되나요...?
@jkey20

**Comment by dev210202** [comment]
일단 테스트용으로 처음 만든거는 3mb인데
30?기부터 지금기수까지 시작하는거라 그렇게 많이는 안들어갈듯
@kimhanui
