### ISSUE TITLE
서버 데이터 추가할것들

### ISSUE THREAD

**Issue by dev210202** [jkey20/Interface_Android#7]
## 캘린더
- 날짜
- 제목
- 내용

## 로그인용 패스워드
- value
- pw

서버에서 value값을 가져와서 value값이 관리자일경우 관리자 로그인, 동아리원일경우 일반 로그인

## member(관리자)
관리자용 정보
- state
- generation
- department
- studentID
- name
- phoneNumber
- contact
- firstDues
- secondDues
- openingMeeting
- finalMeeting

member에 들어가는 정보들은 모두 String형식으로 바꿔주세요

**Comment by jkey20** [comment]
> ## 캘린더
> * 날짜
> * 제목
> * 내용

**Comment by jkey20** [comment]
로그인용 패스워드  
FCM 토큰 저장

2개 추가

**Comment by dev210202** [comment]
서버에서 다음과 같이 처리 가능한지? 가능하다면 다음과 같이 진행
1. insertMeeting으로 관리자가 관리자의 위도 경도를 보냄
2. meet/userCheck로 사용자가 사용자의 위도경도를 보내면 저장되어있는 meeting에 위도경도와 비교
3. 같으면 출석ok, 다르면 x

불가능할시
1. meet/userCheck로 사용자가 사용자의 위도경도를 보냄
2. 관리자가  findAllMember를 통해서 데이터를 받았을 때 위도경도 데이터까지 받음
3. 받은 위도경도 데이터와 관리자의 위도경도 비교해서 출석리스트 표시 

서버에 Firebase key값을 올려도 보안상의 문제가 없는지?

**Comment by kimhanui** [comment]
네 가능, 근데 @jkey20 
- 관리자가 모임 예정 시각 이전에 다른 장소에서 모임 등록한다면 해당 모임 장소와 위,경도가 다를텐데 
  이 부분은 안드에서 따로 설정하나요? -> 이해함

Firebase key값 - 넵 db에 올리거나, 서버 환경변수 설정을 하면 될 것 같아요

**Comment by kimhanui** [comment]
> 캘린더

crud(create,read,update,delete)만들겟슴다


>로그인용 패스워드
>서버에서 value 값을 가져와서 value값이 관리자일경우 관리자 로그인, 동아리원일경우 일반 로그인

안드에서 먼저 서버에 value값 준다는 뜻인가요? 맞다면 어떤 값으로 줄지 알려주세요
`eg. 'member','admin'` 

> member(관리자),Token(관리자)

**관리자**= 관리자가 볼 데이터란 뜻인가요? 맞다면 
`member(관리자)`-> `회원 각각 정보`  
`Token(관리자)`->`FCM과 관련해서 서버에서 안드에 주는 토큰형식` 인가요?

@jkey20

**Comment by dev210202** [comment]
로그인용 패스워드는 서버에 초기 저장값 2개(사용자 패스워드, 관리자 패스워드)가 존재하고 관리자는 이 2개를 수정할 수 있음
패스워드 초기 저장값은 
관리자 interfaceAdmin
사용자 interfaceUser

관리자 = 관리자가 볼 데이터
member는 맞고
Token은 알림 수신거부하는 사람들 토큰받아서 저장해놨다가 안드로이드 실행할때 수신여부 파악해서 수신거부면 알람 안받게 하려고 했는데 알람을 보통 중요할때 쓸꺼니까 그냥 다 받아야할거같아서 안해도 될듯

@kimhanui

**Comment by dev210202** [comment]
> * 관리자가 모임 예정 시각 이전에 다른 장소에서 모임 등록한다면 해당 모임 장소와 위,경도가 다를텐데
>   이 부분은 안드에서 따로 설정하나요?

우리가 출석체크하면 보통 모임 예정시각 이후에 다 모이고나서 체크하는 방식이라 다 모였을 때 관리자가 출석체크를 시작하면 모임 등록이 되는것이 내가 원하는 방식

그리고 캘린더가 있어서 모임하는 날짜는 거기서 확인하고 출석체크는 관리자가 수동으로 열어야 오픈되는식으로
@kimhanui

**Comment by dev210202** [comment]
Token 다시 넣어야함 

앱에서 알람을 전체 사용자한테 보내려면 토큰값을 다 알고있어야해서 서버에서 토큰값을 가져야함

### Token
- token


@kimhanui

**Comment by dev210202** [comment]
# member
- studentId, generation을 String으로 반환되게 해주세요
- sample data에 department가 null인데 아무 텍스트라도 넣어주세요

@kimhanui
