### ISSUE TITLE
서버 에러

### ISSUE THREAD

**Issue by dev210202** [jkey20/Interface_Android#8]
### 상황
URL: https://interface-app-dev.herokuapp.com/api/v1/meet/userCheck

POST로 다음과 같이 메시지를 보냄

- String studentId;
- String name;
- String groupNum;
- String passkey;

ex) {"groupNum":"123","name":"dsd","passkey":"VJ5FG","studentId":"123"}

결과 : 
![image](https://user-images.githubusercontent.com/32587845/102957640-48f0ad00-451e-11eb-841f-5ca1b015fec3.png)

**Comment by kimhanui** [comment]
DB에 들어가있는 passkey정보니까 참고해보삼 @jkey20 
- `createdDateTime` 보다 1초라도 나중, `endDateTime`보다 이전 시간("dateTime"의 value)으로 보내면 됩니다

createdDateTime | endDateTime | passkey
|------|---|---|
2020-11-11 00:00:00.000000 | 2020-11-11 01:00:00.000000 | SSD2K
2020-09-09 00:00:00.000000 | 2020-09-09 01:00:00.000000 | VJ5FG

**Comment by dev210202** [comment]
@kimhanui 
시간도 넣어서 보내줬는데 이렇게 나옴
![image](https://user-images.githubusercontent.com/32587845/103492745-4ec88580-4e70-11eb-8b02-7e427d036966.png)

**Comment by kimhanui** [comment]
아 그 여기보시면 https://github.com/jkey20/Interface_Android/issues/1#issuecomment-752637380 @jkey20 
이미 존재하는 회원 정보를 입력해야하기때문에  
**Doc예제에서 쓴 회원 정보를 입력해야합니다.**
- 다른 회원정보는 몰라도 `studentId`는 일치해야함.

(원랜 날짜만 입력해도됐는데,, 회원 중복추가되는 버그가 잇어서 수정햇어요& doc 설명을 디테일하게 추가하겟습니다)

Ok(응답성공) 예제
```
{
    "studentId":"100100", 
    "name": "kim",
    "groupNum":"30",
    "passkey":"VJ5FG",
    "dateTime":"2020-09-09T00:10"
}
```

**Comment by dev210202** [comment]
그러면 회원등록과 상관없게 암호만 일치하면 패스하게 하도록 바꿔주세요
@kimhanui

**Comment by kimhanui** [comment]
일단 @jkey20 

```  
- 기수, 이름, 학번-> 관리자 직접 확인(눈으로)
- fcmToken 테이블 만들기-> 대리출석 방어(중복출석) & 명부 조회는 토큰만
- 위경도-> 자리에서 출석
```
- `fcmToken` 을 사용자와 어떻게 매치할지 알면 -> `본인 인증`도 할 수 있음.
- 아니면 `중복출석`만 할 수 있음

**Comment by dev210202** [comment]
안드에서 서버로 주는 데이터 -> 기수, 이름, 학번 등등, fcmToken

서버에서 자체처리 -> fcmToken 테이블을 조회해서 중복이면 에러메시지 출력, 중복 아닐시 테이블에 저장

서버에서 안드로 주는 데이터 -> 패스워드별로 저장된 사용자 정보들

@kimhanui  이렇게하고 중복출석 확인만 하자

**Comment by kimhanui** [comment]
@jkey20 


> 안드에서 서버로 주는 데이터 -> 기수, 이름, 학번 등등, fcmToken
> 
> 서버에서 자체처리 -> fcmToken 테이블을 조회해서 중복이면 에러메시지 출력, 중복 아닐시 테이블에 저장
> 
> 서버에서 안드로 주는 데이터 -> 패스워드별로 저장된 사용자 정보들
> 
> @kimhanui 이렇게하고 중복출석 확인만 하자

### 문제점
- 사용자의 토큰이 변경됐을 때 변경대신 추가됨. 누적된 토큰을 처리할 방법 생각해야함.

**Comment by dev210202** [comment]
@kimhanui 
누적되어도 상관없지않을까?
안드로이드 앱이 깔려있지않으면 어차피 알람도 안가고 아니면 1년주기로 초기화한다거나?
